name: 'PR description checker'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled
jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jadrol/pr-description-checker-action@c659fed338a52d657d34462c8bc7fc1f65d25758
        id: description-checker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
